apiVersion: apps/v1
kind: Deployment
metadata:
  name: serve-tcp
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serve-tcp
  template:
    metadata:
      labels:
        app: serve-tcp
    spec:
      containers:
        - name: serve
          image: jeremyot/serve:8680343
          resources:
            limits:
              cpu: 100m
              memory: 50Mi
          args:
            - '--tcp=:6080'
            - '--message=''hello from cluster 1 (Node: {{env "NODE_NAME"}} Pod: {{env "POD_NAME"}} Address: {{addr}})'''
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
